export const Images = {
  VACAKAAI_LOGO: "/Images/VacakaAI-Logo.webp",
  AASTHA: "/Images/Aastha.webp",
  ABOUT_US_BG: "/Images/About-Us-Bg.webp",
  ABOUT_US_PIC: "/Images/About-Us-Pic.webp",
  ANITA_MENON: "/Images/Anita-Menon.webp",
  BLOG_1: "/Images/Blog-1.webp",
  BLOG_2: "/Images/Blog-2.webp",
  BLOG_3: "/Images/Blog-3.webp",
  CAREER_PAGE_1: "/Images/Career-Page-1.webp",
  CAREER_PAGE_2: "/Images/Career-Page-2.webp",
  CAREER_PAGE_3: "/Images/Career-Page-3.webp",
  CAREER_PAGE: "/Images/Career-Page.webp",
  CARTOON_NETWORK_LOGO: "/Images/Cartoon-Network-Logo.webp",
  DEEPASHA: "/Images/Deepasha.webp",
  DISCORD: "/Images/Discord.webp",
  FREDDY_SODAWALLAH: "/Images/Freddy-Sodawallah.webp",
  GREEN_GOLD_LOGO: "/Images/Green-Gold-Logo.webp",
  INSTAGRAM: "/Images/Instagram.webp",
  JI_HOTSTAR_LOGO: "/Images/Ji- Hotstar-Logo.webp",
  KAUSHAL_SETHI: "/Images/Kaushal-Sethi.webp",
  LANDING_PAGE_IMAGE: "/Images/Landing-Page-Image.webp",
  LINKEDIN: "/Images/LinkedIn.webp",
  MEET_TEAM_LINKEDIN: "/Images/Meet-The-Team-LinkedIn.webp",
  MEET_TEAM_WAVE: "/Images/Meet-The-Team-Wave.webp",
  MESSENGER: "/Images/Messenger.webp",
  NDTV_LOGO: "/Images/NDTV-Logo.webp",
  NETFLIX_LOGO: "/Images/Netflix-Logo.webp",
  POGO_LOGO: "/Images/Pogo-Logo.webp",
  RED_CHILLIS_LOGO: "/Images/Red-Chillis-Logo.webp",
  ROHIT_VISTAPLAY: "/Images/Rohit-VistaPlay.webp",
  SAHIL_THAKUR: "/Images/Sahil-Thakur.webp",
  SPOTIFY_LOGO: "/Images/Spotify-Logo.webp",
  TWITTER: "/Images/Twitter.webp",
  VACAKA_AI_LOGO: "/Images/Vacaka-AI-Logo.webp",
  WHATSAPP: "/Images/Whatsapp.webp",
  YELLOW_ARROW: "/Images/Yellow-Arrow.webp",
  YOUTUBE: "/Images/Youtube.webp",
} as const;

export type SVGKey = keyof typeof Images;
